version:  '3'
services:
  datascience-notebook:
    # image:    pydaa/python-data-science
    build: data_science
    volumes:
      - ${HOME}:/home
      - ${LOCAL_DATASETS}:/home/data
      - ${LOCAL_notebook}:/home/notebook
      - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
    ports:
      - ${PORT}:8888
    # container_name: python-data-science
    command: "jupyter lab"
      # --NotebookApp.password=${ACCESS_TOKEN}"
    links:
        - db
    depends_on:
        - db
    runtime: nvidia
  db:
    image:
        postgres
    restart:
        always
    environment:
        POSTGRES_USER:
            pythonista
        POSTGRES_PASSWORD:
            password
        POSTGRES_DB:
            mypyenv
    ports:
        - "5432"
    container_name:
        postgres-db
    volumes:
        - ./postgres-db:/var/lib/postgresql/data
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
