version:  '3'
services:
  datascience-notebook:
    # image:    pydaa/python-data-science
    build: data_science
    volumes:
      - ${HOME}/dev:/home
      - ${HOME}/data:/home/data
      - ${HOME}/notebook:/home/notebook
    ports:
      - ${PORT}:8888
    # container_name: python-data-science
    command: "jupyter lab"
      # --NotebookApp.password=${ACCESS_TOKEN}"
